namespace Synaptics.Domain.Enums;

public enum MessageCode
{
    SomethingWrong,
    TokenNotFound,
    SessionNotFound,
    CredentialsWrong,
    UserNotExists,
    UserExistsThisEmail, 
    UserExistsThisUserName,
    PasswordsCantBeSame,
    YouCantFollowYourself,
    YouDoNotFollowYourselfAnyway,
    PostNotExists,
    YouArentAllowedEditPost,
    YouArentAllowedDeletePost,
    YouArentAllowedRecoverPost,
    YouAlreadyLikedPost,
    YouArentLikedPost,
    YouAlreadyFollowUser,
    YouArentFollowUser,
    UserIsntFollowYou,
    UserHasNoPosts,
    CommentNotExists,
    YouAlreadyLikedComment,
    YouArentAllowedEditComment,
    YouArentAllowedDeleteComment,
    YouArentLikedComment,
}
